jest.mock('@folio/stripes-inventory-components', () => {
  const actual = jest.requireActual('@folio/stripes-inventory-components');
  return {
    ...actual,
    getSearchTerm: jest.fn(),
    deleteFacetStates: jest.fn(),
    resetFacetStates: jest.fn(),
    resetFacetSearchValue: jest.fn(),
    useFacetStates: jest.fn(() => () => {}),
    useResetFacetStates: jest.fn(() => () => {}),
    useSearchValue: jest.fn(() => () => {}),
    useLocationsQuery: jest.fn().mockReturnValue({
      locations: [],
      isLoading: false,
    }),
    useCommonData: jest.fn().mockReturnValue({
      commonData: [],
      isCommonDataLoading: false,
    }),
    browseModeOptions: actual.browseModeOptions || {
      CALL_NUMBERS: 'callNumbers',
      DEWEY: 'dewey',
      LIBRARY_OF_CONGRESS: 'lc',
      LOCAL: 'local',
      NATIONAL_LIBRARY_OF_MEDICINE: 'nlm',
      OTHER: 'other',
      SUPERINTENDENT: 'sudoc',
      CLASSIFICATION_ALL: 'classificationAll',
      DEWEY_CLASSIFICATION: 'deweyClassification',
      LC_CLASSIFICATION: 'lcClassification',
      CONTRIBUTORS: 'contributors',
      SUBJECTS: 'browseSubjects',
    },
    queryIndexes: actual.queryIndexes || {
      INSTANCE_KEYWORD: 'instanceKeyword',
      TITLE: 'title',
      IDENTIFIER: 'identifier',
      NORMALIZED_CLASSIFICATION_NUMBER: 'normalizedClassificationNumber',
      ISBN: 'isbn',
      ISSN: 'issn',
      LCCN: 'lccn',
      OCLC: 'oclc',
      INSTANCE_NOTES: 'instanceNotes',
      INSTANCE_ADMINISTRATIVE_NOTES: 'instanceAdministrativeNotes',
      PLACE_OF_PUBLICATION: 'placeOfPublication',
      SUBJECT: 'subject',
      INSTANCE_HRID: 'hrid',
      INSTANCE_ID: 'id',
      AUTHORITY_ID: 'authorityId',
      ALL_FIELDS: 'allFields',
      QUERY_SEARCH: 'querySearch',
      CALL_NUMBER: 'callNumber',
      DEWEY: 'dewey',
      LIBRARY_OF_CONGRESS: 'lc',
      LOCAL: 'local',
      NATIONAL_LIBRARY_OF_MEDICINE: 'nlm',
      OTHER: 'other',
      SUPERINTENDENT: 'sudoc',
      CLASSIFICATION_ALL: 'classificationAll',
      DEWEY_CLASSIFICATION: 'deweyClassification',
      LC_CLASSIFICATION: 'lcClassification',
      CONTRIBUTOR: 'contributor',
      ADVANCED_SEARCH: 'advancedSearch',
      HOLDINGS_KEYWORD: 'holdingsKeyword',
      HOLDINGS_FULL_CALL_NUMBERS: 'holdingsFullCallNumbers',
      CALL_NUMBER_NORMALIZED: 'callNumberNormalized',
      HOLDINGS_NOTES: 'holdingsNotes',
      HOLDINGS_ADMINISTRATIVE_NOTES: 'holdingsAdministrativeNotes',
      HOLDINGS_HRID: 'holdingsHrid',
      HOLDINGS_ID: 'holdingsId',
      ITEMS_KEYWORD: 'itemsKeyword',
      ITEMS_BARCODE: 'items.barcode',
      ITEM_FULL_CALL_NUMBERS: 'itemFullCallNumbers',
      ITEM_NORMALIZED_CALL_NUMBERS: 'itemNormalizedCallNumbers',
      ITEM_NOTES: 'itemNotes',
      ITEM_ADMINISTRATIVE_NOTES: 'itemAdministrativeNotes',
      ITEM_CIRCULATION_NOTES: 'itemCirculationNotes',
      ITEM_HRID: 'itemHrid',
      ITEM_ID: 'iid',
    },
    InstanceFilters: jest.fn(() => <div>InstanceFilters</div>),
    HoldingsRecordFilters: jest.fn(() => <div>HoldingsRecordFilters</div>),
    ItemFilters: jest.fn(() => <div>ItemFilters</div>),
    buildSearchQuery: jest.fn(),
  };
});
